kind: ConfigMap
apiVersion: v1
metadata:
  name: db-env
data: 
  EXTERNAL_DB_USERNAME: user
  EXTERNAL_DB_PASSWORD: pass
  EXTERNAL_DB_JDBC_URL: jdbc:postgresql://postgresql.rhsso.svc.cluster.local/sampledb