kind: ConfigMap
apiVersion: v1
metadata:
  name: db-env
data: 
  EXTERNAL_DB_USERNAME: service-user
  EXTERNAL_DB_PASSWORD: pass
  EXTERNAL_DB_JDBC_URL: jdbc:postgresql://crdb-tls-example.rhsso.svc.cluster.local:26257/tas-application-content-db?sslmode=require